mainapp/urls.py
from django.urls import path
from . import views
from .views import (
    ItemDetailView,
    CheckoutView,
    
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView
)

app_name = 'core'


urlpatterns = [
   path("",views.index,name='index' ),
   path("allbeer",views.allbeer,name='allbeer' ),
   path("alldetail/<slug:slug>/",views.alldetail,name='alldetail' ),
   path("about",views.about,name='aboutus' ),
   path("detail",views.detail,name='detail' ),
   path("confirm",views.confirm,name='confirm' ),
   #path("order-summary/",views.order_summary_view,name='order-summary' ),
#    path('add_too_cart/', views.add_too_cart, name='add_to_cart'),
#    #path('cart/remove/', views.remove_from_cart, name='remove_from_cart'),
#    path('remove-from-cart/',views.remove_from_cart, name='remove_from_cart'),
#     path('get_cart_count/', views.get_cart_count, name='get_cart_count'),



    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug:slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug:slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('add-single-item-to-cart/<int:item_id>/', views.add_single_item_to_cart, name='add-single-item-to-cart'),

    path('remove-from-cart/<int:item_id>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<int:item_id>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

mainpro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('mainapp.urls')),
    path("", include('userauth.urls')),
    path('accounts/', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)


class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    shipping_zip = forms.CharField(required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    billing_zip = forms.CharField(required=False)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))


class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))
    email = forms.EmailField()


class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)

mainapp/views.py
from django.shortcuts import render
from . models import Item
from django.shortcuts import render, get_object_or_404
# Create your views here.


def index(request):
    #food = Category.objects.get(name='food')
    items_in_category = Item.objects.filter(category='SW')
    beer = Item.objects.filter(category='S')
    #alchol_drink = Category.objects.get(name='alcholic')
    #beer=Item.objects.filter(category=alchol_drink)
    context={
        'beer':beer,
        'food':items_in_category
    }
    return render(request,'mainapp/index.html',context)

# from django.shortcuts import get_object_or_404
# from .models import Items

def alldetail(request, slug):
    # Get the specific product by ID
    obj = get_object_or_404(Item, slug=slug)
    
    # Get related items in the same category, excluding the current product
    related_items = Item.objects.filter(category=obj.category).exclude(slug=obj.slug)[:4]  # Limit to 8 items

    context = {
        'obj': obj,
        'related_items': related_items,
    }
    
    return render(request, 'mainapp/detail.html', context)


def allbeer(request):
    return render(request,'main/allbeer.html')


def detail(request):
    return render(request,'mainapp/lol.html')

def about(request):
    return render(request,'main/about.html')

def confirm(request):
    return render(request,'main/confirm.html')





import random
import string

import stripe
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.views.generic import ListView, DetailView, View

from .forms import CheckoutForm, CouponForm, RefundForm, PaymentForm
from .models import Item, OrderItem, Order, Address, Payment, Coupon, Refund, UserProfile

#stripe.api_key = settings.STRIPE_SECRET_KEY


def create_ref_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))


def products(request):
    context = {
        'items': Item.objects.all()
    }
    return render(request, "core/index.html", context)


def is_valid_form(values):
    valid = True
    for field in values:
        if field == '':
            valid = False
    return valid


class CheckoutView(View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            form = CheckoutForm()
            context = {
                'form': form,
                'couponform': CouponForm(),
                'order': order,
                'DISPLAY_COUPON_FORM': True
            }

            shipping_address_qs = Address.objects.filter(
                user=self.request.user,
                address_type='S',
                default=True
            )
            if shipping_address_qs.exists():
                context.update(
                    {'default_shipping_address': shipping_address_qs[0]})

            billing_address_qs = Address.objects.filter(
                user=self.request.user,
                address_type='B',
                default=True
            )
            if billing_address_qs.exists():
                context.update(
                    {'default_billing_address': billing_address_qs[0]})
            return render(self.request, "core/checkout.html", context)
        except ObjectDoesNotExist:
            messages.info(self.request, "You do not have an active order")
            return redirect("core:checkout")

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():

                use_default_shipping = form.cleaned_data.get(
                    'use_default_shipping')
                if use_default_shipping:
                    print("Using the defualt shipping address")
                    address_qs = Address.objects.filter(
                        user=self.request.user,
                        address_type='S',
                        default=True
                    )
                    if address_qs.exists():
                        shipping_address = address_qs[0]
                        order.shipping_address = shipping_address
                        order.save()
                    else:
                        messages.info(
                            self.request, "No default shipping address available")
                        return redirect('core:checkout')
                else:
                    print("User is entering a new shipping address")
                    shipping_address1 = form.cleaned_data.get(
                        'shipping_address')
                    shipping_address2 = form.cleaned_data.get(
                        'shipping_address2')
                    shipping_country = form.cleaned_data.get(
                        'shipping_country')
                    shipping_zip = form.cleaned_data.get('shipping_zip')

                    if is_valid_form([shipping_address1, shipping_country, shipping_zip]):
                        shipping_address = Address(
                            user=self.request.user,
                            street_address=shipping_address1,
                            apartment_address=shipping_address2,
                            country=shipping_country,
                            zip=shipping_zip,
                            address_type='S'
                        )
                        shipping_address.save()

                        order.shipping_address = shipping_address
                        order.save()

                        set_default_shipping = form.cleaned_data.get(
                            'set_default_shipping')
                        if set_default_shipping:
                            shipping_address.default = True
                            shipping_address.save()

                    else:
                        messages.info(
                            self.request, "Please fill in the required shipping address fields")

                use_default_billing = form.cleaned_data.get(
                    'use_default_billing')
                same_billing_address = form.cleaned_data.get(
                    'same_billing_address')

                if same_billing_address:
                    billing_address = shipping_address
                    billing_address.pk = None
                    billing_address.save()
                    billing_address.address_type = 'B'
                    billing_address.save()
                    order.billing_address = billing_address
                    order.save()

                elif use_default_billing:
                    print("Using the defualt billing address")
                    address_qs = Address.objects.filter(
                        user=self.request.user,
                        address_type='B',
                        default=True
                    )
                    if address_qs.exists():
                        billing_address = address_qs[0]
                        order.billing_address = billing_address
                        order.save()
                    else:
                        messages.info(
                            self.request, "No default billing address available")
                        return redirect('core:checkout')
                else:
                    print("User is entering a new billing address")
                    billing_address1 = form.cleaned_data.get(
                        'billing_address')
                    billing_address2 = form.cleaned_data.get(
                        'billing_address2')
                    billing_country = form.cleaned_data.get(
                        'billing_country')
                    billing_zip = form.cleaned_data.get('billing_zip')

                    if is_valid_form([billing_address1, billing_country, billing_zip]):
                        billing_address = Address(
                            user=self.request.user,
                            street_address=billing_address1,
                            apartment_address=billing_address2,
                            country=billing_country,
                            zip=billing_zip,
                            address_type='B'
                        )
                        billing_address.save()

                        order.billing_address = billing_address
                        order.save()

                        set_default_billing = form.cleaned_data.get(
                            'set_default_billing')
                        if set_default_billing:
                            billing_address.default = True
                            billing_address.save()

                    else:
                        messages.info(
                            self.request, "Please fill in the required billing address fields")

                payment_option = form.cleaned_data.get('payment_option')

                if payment_option == 'S':
                    return redirect('core:payment', payment_option='stripe')
                elif payment_option == 'P':
                    return redirect('core:payment', payment_option='paypal')
                else:
                    messages.warning(
                        self.request, "Invalid payment option selected")
                    return redirect('core:checkout')
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("core:order-summary")


class PaymentView(View):
    def get(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        if order.billing_address:

mainapp/templates/mainapp/checkout.html
{% comment %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checkout Page</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background: #f6f8fd;
            margin: 20px;
        }

        .container {
            max-width: 1200px;
            margin: auto;
            background: white;
            border-radius: 10px;
            overflow: hidden;
            display: flex;
            flex-direction: column;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
        }

        .header {
            padding: 15px;
            background: #ffffff;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .header a {
            text-decoration: none;
            color: #000;
            font-weight: bold;
        }

        .content {
            display: flex;
            padding: 20px;
            flex-wrap: wrap;
        }

        .left-section {
            flex: 2;
            padding: 15px;
        }

        .right-section {
            flex: 1;
            background: #f9f9f9;
            padding: 20px;
            border-left: 1px solid #ddd;
        }

        .radio-group {
            display: flex;
            flex-direction: column;
            gap: 10px;
        }

        .radio-group label {
            display: flex;
            align-items: center;
            gap: 10px;
            cursor: pointer;
        }

        .shipping-address {
            margin-top: 20px;
        }

        .payment-info {
            margin-top: 20px;
        }

        .input-group {
            margin-bottom: 15px;
        }

        .input-group input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
        }

        .order-summary {
            margin-top: 20px;
        }

        .order-summary ul {
            list-style: none;
        }

        .order-summary ul li {
            margin-bottom: 10px;
            display: flex;
            justify-content: space-between;
        }

        .confirm-btn {
            background: #7a5af8;
            color: white;
            padding: 15px;
            width: 100%;
            border: none;
            cursor: pointer;
            font-size: 16px;
            border-radius: 5px;
        }

        @media (max-width: 768px) {
            .content {
                flex-direction: column;
            }

            .right-section {
                border-left: none;
                margin-top: 20px;
            }
        }
    </style>
</head>
<body>
  
    <div class="container">
        <div class="header">
          
            <a href="#">Saba</a>
            <nav>
                <a href="#">New arrival</a>
                <a href="#">Women</a>
                <a href="#">Men</a>
                <a href="#">Outlet</a>
            </nav>
        </div>

        <div class="content">
            <div class="left-section">
                <div class="radio-group">
                    <label>
                        <input type="radio" name="delivery" checked>
                        Get it delivered in only 30 minutes
                    </label>
                    <label>
                        <input type="radio" name="delivery">
                        Pickup available in 3 stores near you
                    </label>
                </div>

                <div class="shipping-address">
                    <label for="address">Shipping address</label>
                    <input type="text" id="address" value="98 Kile Close, 8-3, Marsfield, Sydney Australia 2723">
                </div>

                <div class="payment-info">
                    <label>Payment Information</label>
                    <div class="input-group">
                        <input type="text" placeholder="Name on card">
                    </div>
                    <div class="input-group">
                        <input type="text" placeholder="Card number">
                    </div>
                    <div class="input-group" style="display: flex; gap: 10px;">
                        <input type="text" placeholder="MM/YY">
                        <input type="text" placeholder="CVV">
                    </div>
                </div>

                <button class="confirm-btn">Confirm Payment $570.98</button>
            </div>

            <div class="right-section">
                <div class="order-summary">
                    <h3>Order Summary</h3>
                    <ul>
                        <li><span>Franklin Merino Wool V-Neck Knit</span><span>$199.00</span></li>
                        <li><span>Judd Slim Dress Chino Pant</span><span>$159.00</span></li>
                        <li><span>Angus Shawl Cardigan</span><span>$199.99</span></li>
                        <li><span>Delivery</span><span>$16.99</span></li>
                        <li><span>Discount</span><span>$0.00</span></li>
                        <li><span>Total (exc tax)</span><span>$557.99</span></li>
                        <li><span>Tax</span><span>$12.99</span></li>
                        <li><strong>Order Total</strong><strong>$570.98</strong></li>
                    </ul>
                </div>

                <div class="coupon">
                    <input type="text" placeholder="Coupon code">
                    <button>Apply</button>
                </div>
            </div>
        </div>
    </div>
</body>
</html> {% endcomment %}

mainapp/templates/mainapp/order_snippet.html
{% comment %} <div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>
 {% endcomment %}

mainapp/templates/mainapp/order_summary.html
{% comment %} {% extends "mainapp/base.html" %}

{% block content %}

<style>
    * {
        color: white;
    }

    h2 {
        color: #ffffff;
        font-size: 2rem;
        margin-bottom: 20px;
    }

    table {
        width: 100%;
    }

    th, td {
        text-align: center;
        padding: 12px;
    }

    .table thead th {
        background-color: #333;
        border-bottom: 2px solid #fff;
    }

    .table tbody tr:nth-child(even) {
        background-color: #444;
    }

    .table tbody tr:hover {
        background-color: #555;
    }

    .badge-primary {
        background-color: #007bff;
    }

    /* Stylish buttons */
    .btn {
        font-size: 1rem;
        padding: 10px 20px;
        margin-top: 10px;
        border-radius: 25px; /* Rounded buttons */
        transition: all 0.3s ease-in-out; /* Smooth animation */
        text-transform: uppercase; /* Capitalize button text */
        letter-spacing: 1px; /* Add some spacing between letters */
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

    .btn-warning {
        background-color: #ffc107;
        border-color: #ffc107;
    }

    .btn-primary:hover,
    .btn-warning:hover {
        opacity: 0.8;
        transform: scale(1.1); /* Slightly enlarge on hover */
        box-shadow: 0 4px 10px rgba(0, 123, 255, 0.4); /* Add a shadow effect on hover */
    }

    .btn-primary:active,
    .btn-warning:active {
        transform: scale(1); /* Reset the scale when button is pressed */
    }

    /* Flex container for buttons */
    .button-container {
        display: flex;
        justify-content: space-between; /* Space between buttons */
        gap: 10px; /* Space between buttons */
        flex-wrap: wrap; /* Ensure buttons wrap on smaller screens */
    }

    .float-right {
        float: right;
    }

    .text-nowrap {
        white-space: nowrap;
    }

    .table-responsive {
        overflow-x: auto;
        -webkit-overflow-scrolling: touch;
    }

    /* Responsive adjustments */
    @media (max-width: 768px) {
        th, td {
            font-size: 0.9rem;
            padding: 8px;
        }

        h2 {
            font-size: 1.5rem;
        }

        /* Make buttons full-width on small screens */
        .btn {
            width: 100%;
            margin: 5px 0;
        }
    }

    /* Style for item images */
    .item-image {
        width: 50px;
        height: 50px;
        object-fit: cover;
        border-radius: 8px;
    }
</style>

<main class="mt-5">
    <div class="container text-white">

        <div class="table-responsive text-nowrap">
            <h2>Order Summary</h2>
            <table class="table">
                <thead>
                    <tr class="text-white">
                        <th scope="col">Image</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <td>
                            <img src="{{ order_item.item.image.url }}" alt="{{ order_item.item.title }}" class="item-image">
                        </td>
                        <td>${{ order_item.item.price }}</td>
                        <td>
                            <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}">
                                <i class="fas fa-minus mr-2"></i>
                            </a>
                            {{ order_item.quantity }}
                            <a href="{% url 'core:add-to-cart' order_item.item.slug %}">
                                <i class="fas fa-plus ml-2"></i>
                            </a>
                        </td>
                        <td>
                            {% if order_item.item.discount_price %}
                                ${{ order_item.get_total_discount_item_price }}
                                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                            {% else %}
                                ${{ order_item.get_total_item_price }}
                            {% endif %}
                            <a style="color: red;" href="{% url 'core:remove-from-cart' order_item.item.id %}">
                                <i class="fas fa-trash float-right"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4" class="text-center">Your cart is empty</td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            <a class="btn btn-primary float-right" href="/">Continue shopping</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% if object.coupon %}
                    <tr>
                        <td colspan="3"><b>Coupon</b></td>
                        <td><b>-${{ object.coupon.amount }}</b></td>
                    </tr>
                    {% endif %}
                    {% if object.get_total %}
                    <tr>
                        <td colspan="3"><b>Order Total</b></td>
                        <td><b>${{ object.get_total }}</b></td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            <div class="button-container">
                                <a class="btn btn-warning" href="/checkout/">Proceed to checkout</a>
                                <a class="btn btn-primary" href="/">Continue shopping</a>
                            </div>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>

    </div>
</main>

{% endblock content %} {% endcomment %}